In [15]:
def switch(questao):
    if questao == 1:
        # TODO: 1. Ler vetor
        # TODO: 1.I. Ler vetor
        from def_trabalhando_com_vetor import cria_vetor

        # TODO: 1.II. Imprimir vetor
        vetor = cria_vetor()

        # TODO: 1.III. Ordenar vetor inversamente
        from def_trabalhando_com_vetor import ordenar_vetor
        vetor = ordenar_vetor(vetor, o='dec')
        print(f"\n    Vetor Ordenado de Forma Decrescente: {vetor}")

        # TODO: 1.IV. Mostrar
        # TODO: 1.IV.ii Mostrar
        # TODO: 1.IV.i.a. Mostrar Média
        from def_trabalhando_com_vetor import media_vetor
        print(f"\n    Média: {media_vetor(vetor)}")

        # TODO: 1.IV.i.b. Mostrar Mediana
        from def_trabalhando_com_vetor import mediana_vetor
        print(f"\n    Mediana: {mediana_vetor(vetor)}")

        # TODO: 1.IV.i.c. Mostrar Desvio Padrão
        from def_trabalhando_com_vetor import desvio_padrao_vetor
        print(f"\n    Desvio Padrao: {desvio_padrao_vetor(vetor)}")

    elif questao == 2:
        # TODO: 2. Verificar se ano bissexto
        from def_ano_bissexto import ano_bissexto
        print(ano_bissexto())

    elif questao == 3:
        # TODO: 3. Receber um vetor de String e acrescentar uma String ao final de cada index desse vetor
        from def_concatena_vetor_string import concat_str_vetor_str
        frase = concat_str_vetor_str()
        print(f"\n    A frase final ficou: {frase}")

    elif questao == 4:  # valido para questao 5, 6, 7 e 8
        # TODO: 4, 5, 6, 7 e 8
        print("    POR FAVOR, RODAR CELULAS A BAIXO PARA MELHOR VISUALIZAÇÃO...")

    elif questao == 9:
        # TODO: 9. Procure na internet um arquivo JSON...
        # TODO: 9.I. Abrir
        # with open("json_example.js", "r") as json_file:
        #    j_file = json.load(json_file)
        import json
        import requests
        url = "https://itunes.apple.com/gb/rss/customerreviews/id=1500780518/sortBy=mostRecent/json"
        r = requests.get(url)
        j_data = r.json()
        # Mostrando arquivo aberto
        print("    Vá para a pasta do arquivo e verifique o arquivo json_example. Se ele não existia, foi criado.")
        # TODO: 9.II. Converter para dicionario
        # Mostrando arquivo com dtype de dict
        print(f"    O tipo de dtype do arquivo é: {type(j_data)}")
        # TODO: 9.III. Salvar em JSON novamente
        with open("json_example.js", "w") as json_file:
            # j_file.update(j_data)
            json.dump(j_data, json_file, indent=4)
        print("    O dicionário foi salvo no JSON file")

    elif questao == 11:
        # TODO: 11. Manipular JSON nested
        import json
        from def_media_json import media_json
        # Abrindo arquivo JSON
        with open("json_example.js", "r") as json_file:
            j_file = json.load(json_file)
        # Armazenando lista de dicionarios para iterar linha a linha
        dicts_in_list = j_file['feed']["entry"]
        # Passando à função que retorna média de votação
        print(f"    A média das notas dos usuários foi: {media_json(dicts_in_list)}")

    elif questao == 10:
        # TODO: 10. Retornar o enésimo número da sequência de fibonacci
        from def_enesimo_fibonacci import enesimo_fibonacci
        # TODO: 10.II. Retornar resultado
        print(f"    O valor é: {enesimo_fibonacci(int(input('Forneca enesimo numero: ')))}")


switch(int(input("Selecione uma questão: ")))

Selecione uma questão: 4
    POR FAVOR, RODAR CELULAS A BAIXO PARA MELHOR VISUALIZAÇÃO...

### TODO: 4. Procure   na   internet   um   arquivo   .csv   e   transforme-o   em   DataFrame   utilizando   a biblioteca Pandas

In [17]:
import pandas as pd
df = pd.read_csv("India_Menu.csv")
df.head()

,Menu Category,Menu Items,Per Serve Size,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
0,Regular Menu,McVeggie™ Burger,168 g,402.05,10.24,13.83,5.34,0.16,2.49,56.54,7.90,4.49,706.13
1,Regular Menu,McAloo Tikki Burger®,146 g,339.52,8.50,11.31,4.27,0.20,1.47,50.27,7.05,4.07,545.34
2,Regular Menu,McSpicy™ Paneer Burger,199 g,652.76,20.29,39.45,17.12,0.18,21.85,52.33,8.35,5.27,1074.58
3,Regular Menu,Spicy Paneer Wrap,250 g,674.68,20.96,39.10,19.73,0.26,40.93,59.27,3.50,1.08,1087.46
4,Regular Menu,American Veg Burger,177 g,512.17,15.30,23.45,10.51,0.17,25.24,56.96,7.85,4.76,1051.24

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Menu Category           141 non-null    object
 1   Menu Items              141 non-null    object
 2   Per Serve Size          141 non-null    object
 3   Energy (kCal)           141 non-null    float64
 4   Protein (g)             141 non-null    float64
 5   Total fat (g)           141 non-null    float64
 6   Sat Fat (g)             141 non-null    float64
 7   Trans fat (g)           141 non-null    float64
 8   Cholesterols (mg)       141 non-null    float64
 9   Total carbohydrate (g)  141 non-null    float64
 10  Total Sugars (g)        141 non-null    float64
 11  Added Sugars (g)        141 non-null    float64
 12  Sodium (mg)             140 non-null    float64
dtypes: float64(10), object(3)
memory usage: 14.4+ KB

In [19]:
def remove_units (DataFrame, columns, args):
    for col in columns:
        for item in args:
            DataFrame[col] = DataFrame[col].str.strip(item)

remove_units(df, ['Per Serve Size'], [' ', 'g', 'ml'])
df.head()

,Menu Category,Menu Items,Per Serve Size,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
0,Regular Menu,McVeggie™ Burger,168,402.05,10.24,13.83,5.34,0.16,2.49,56.54,7.90,4.49,706.13
1,Regular Menu,McAloo Tikki Burger®,146,339.52,8.50,11.31,4.27,0.20,1.47,50.27,7.05,4.07,545.34
2,Regular Menu,McSpicy™ Paneer Burger,199,652.76,20.29,39.45,17.12,0.18,21.85,52.33,8.35,5.27,1074.58
3,Regular Menu,Spicy Paneer Wrap,250,674.68,20.96,39.10,19.73,0.26,40.93,59.27,3.50,1.08,1087.46
4,Regular Menu,American Veg Burger,177,512.17,15.30,23.45,10.51,0.17,25.24,56.96,7.85,4.76,1051.24

In [23]:
def to_type(DataFrame, columns, type):
    for col in columns:
        if type == "int":
            print("entrou")
            DataFrame[col] = DataFrame[col].round()
        DataFrame[col] = DataFrame[col].astype(type)

to_type(df, ['Per Serve Size'], 'float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Menu Category           141 non-null    object
 1   Menu Items              141 non-null    object
 2   Per Serve Size          141 non-null    float64
 3   Energy (kCal)           141 non-null    float64
 4   Protein (g)             141 non-null    float64
 5   Total fat (g)           141 non-null    float64
 6   Sat Fat (g)             141 non-null    float64
 7   Trans fat (g)           141 non-null    float64
 8   Cholesterols (mg)       141 non-null    float64
 9   Total carbohydrate (g)  141 non-null    float64
 10  Total Sugars (g)        141 non-null    float64
 11  Added Sugars (g)        141 non-null    float64
 12  Sodium (mg)             140 non-null    float64
dtypes: float64(11), object(2)
memory usage: 14.4+ KB

***
    II. Criar nova coluna a partir dos dados de outra coluna
        i. Criar função para pesquisar o index da coluna que se deseja criar uma variação
        ii. Modificar
        iii. Adicioná-la ao dataframe

In [24]:
new_column = df['Per Serve Size'][:] * 1.0

def search_column_name(DataFrame, name):
    for index, header in enumerate(DataFrame.keys()):
        if header == name:
            return index
        
        
insert_index = search_column_name(df, 'Per Serve Size')
df.insert(insert_index, 'perServeSize', new_column)
df.head()

,Menu Category,Menu Items,perServeSize,Per Serve Size,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
0,Regular Menu,McVeggie™ Burger,168.0,168.0,402.05,10.24,13.83,5.34,0.16,2.49,56.54,7.90,4.49,706.13
1,Regular Menu,McAloo Tikki Burger®,146.0,146.0,339.52,8.50,11.31,4.27,0.20,1.47,50.27,7.05,4.07,545.34
2,Regular Menu,McSpicy™ Paneer Burger,199.0,199.0,652.76,20.29,39.45,17.12,0.18,21.85,52.33,8.35,5.27,1074.58
3,Regular Menu,Spicy Paneer Wrap,250.0,250.0,674.68,20.96,39.10,19.73,0.26,40.93,59.27,3.50,1.08,1087.46
4,Regular Menu,American Veg Burger,177.0,177.0,512.17,15.30,23.45,10.51,0.17,25.24,56.96,7.85,4.76,1051.24

### TODO: 6. Aplicar ferramenta Group By
    I. Aplicar ferramenta Group By
    II. Apresentar resultados

In [25]:
df.groupby(['Per Serve Size']).mean()

,perServeSize,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
Per Serve Size,,,,,,,,,,,
5.0,5.0,17.130000,0.510000,0.36,0.080,0.010,0.05,2.500000,0.660,0.40,414.710000
8.0,8.0,11.230000,0.080000,23.45,0.000,0.010,0.08,2.630000,2.330,1.64,71.050000
10.0,10.0,8.070000,0.030000,0.01,0.010,0.010,0.10,1.990000,1.530,1.34,65.240000
14.0,14.0,51.030000,3.060000,3.99,2.890,0.010,13.43,0.720000,0.540,0.00,178.950000
25.0,25.0,68.035000,0.390000,3.03,0.965,0.255,0.27,9.800000,7.155,3.25,167.275000
...,...,...,...,...,...,...,...,...,...,...,...
405.0,405.0,251.470000,12.080000,14.02,10.310,0.410,42.55,22.220000,16.810,0.00,180.800000
455.0,455.0,26.710000,1.090000,0.06,0.060,0.060,0.55,5.300000,0.280,0.00,0.650000
456.0,456.0,12.643333,0.746667,0.46,0.460,0.460,4.56,3.193333,2.280,0.00,23.606667
500.0,500.0,0.000000,0.000000,0.00,0.000,0.000,0.00,0.000000,0.000,0.00,2.900000
544.0,544.0,227.240000,0.000000,0.00,0.000,0.000,0.00,56.810000,56.810,56.81,51.510000

### TODO: 8. Salvar data frame em um arquivo .csv
    I. Salvar data frame em um arquivo .csv
    II. Mostrar resultados

In [26]:
df.to_csv("daniel_scheicher_pandas.csv")